language: r
r:
  - devel
sudo: false
cache: packages
warnings_are_errors: true
cran: http://cran.rstudio.com
addons:
  apt:
    update: true
    packages:
      - libgs-dev
      - qpdf
      - ghostscript